version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    networks:
      - products
  server:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    entrypoint:
      - swagger
      - project
      - start
    volumes:
      - /app/node_modules
      - ./config:/app/config
      - ./api:/app/api
      - ./db:/app/db
      - ./app.js:/app/app.js
    depends_on:
      - db
    networks:
      - products

networks:
  products:
