version: '3'
services:
  server:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    entrypoint:
      - swagger
      - project
      - start
    volumes:
      - /app/node_modules
      - ./config:/app/config
      - ./api:/app/api
      - ./test:/app/test
      - ./app.js:/app/app.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
